### ISSUE TITLE
`countrycode` reverse dependency break

### ISSUE THREAD

**Issue by vincentarelbundock** [rOpenGov/giscoR#81]
Hi,

I maintain the `countrycode` package and it looks like the upcoming version will cause a break in your package. The issue seems minor, related only to a reference in the documentation:

```r
Changes to worse in reverse depends:

Package: giscoR
Check: Rd cross-references
New result: WARNING
  Missing link or links in Rd file 'gisco_countrycode.Rd':
    ‘[countrycode:countrycode-package]{countrycode::countrycode-package}’
  
  See section 'Cross-references' in the 'Writing R Extensions' manual.
```

Sorry for the trouble!

**Comment by dieghernan** [comment]
Hi @vincentarelbundock 

No worries, this is very minor, I'll fix it by next week. Unfortunately #80 is already on CRAN (I forgot to close it) so I have to wait at least one week to avoid check complains.

Regards and thanks for the heads-up!
